// Shared hobby/project type options used by the board form and community search
export const HOBBY_TYPES = [
  "3D Printing",
  "Astronomy",
  "Beekeeping",
  "Birdwatching",
  "Board Games",
  "Boating",
  "Calligraphy",
  "Camping & Outdoors",
  "Cars",
  "Coding & Software",
  "Collecting",
  "Cooking & Baking",
  "Cosplay & Costuming",
  "Cycling",
  "Dance",
  "Drone Flying",
  "Electronics",
  "Fishing",
  "Fitness",
  "Gaming",
  "Gardening",
  "Home Brewing",
  "Home DIY",
  "Interior Design",
  "Jewelry Making",
  "Journaling & Scrapbooking",
  "Knitting & Crochet",
  "Leatherworking",
  "Metalworking",
  "Model Building",
  "Motorcycles",
  "Music",
  "Painting & Drawing",
  "Photography",
  "Pottery & Ceramics",
  "RC Vehicles",
  "Robotics",
  "Rock Climbing",
  "Sewing",
  "Video Editing",
  "Woodworking",
  "Writing",
  "Yoga & Meditation",
  "Other",
];
