"""add indexes for foreign keys and filtered columns

Revision ID: 5c9a81742f7e
Revises: 
Create Date: 2026-09-10 20:53:06.862518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9a81742f7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_follows_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_follows_follower_user_id'), ['follower_user_id'], unique=False)

    with op.batch_alter_table('board_update_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_update_comments_update_id'), ['update_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_update_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('board_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_updates_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_updates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_follows_followed_user_id'), ['followed_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follows_follower_user_id'), ['follower_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follows_follower_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_follows_followed_user_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_board_id'))

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_user_id'))

    with op.batch_alter_table('board_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_updates_user_id'))
        batch_op.drop_index(batch_op.f('ix_board_updates_board_id'))

    with op.batch_alter_table('board_update_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_update_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_board_update_comments_update_id'))

    with op.batch_alter_table('board_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_follows_follower_user_id'))
        batch_op.drop_index(batch_op.f('ix_board_follows_board_id'))

    # ### end Alembic commands ###
